name: Compile typescript

on: [push, pull_request]

jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: yarn --immutable
      - name: Compile
        run: yarn compile
